name: Run tests

on: [pull_request, fork, workflow_dispatch]

jobs:

  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    env:
      ARANGODB_VER: 3.9.1
      ARANGODB_V: 39
    steps:

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check out GitHub repo
      if: "!contains(github.event.head_commit.message, 'skip ci')"
      uses: actions/checkout@v2

    - name: Set up test environment
      if: "!contains(github.event.head_commit.message, 'skip ci')"
      shell: bash
      run: |
        python --version
        which python
        export ARANGO_FILE=arangodb3-linux-$ARANGODB_VER.tar.gz
        wget -nv https://download.arangodb.com/arangodb$ARANGODB_V/Community/Linux/$ARANGO_FILE
        tar xfz $ARANGO_FILE

        pip install pipenv
        pipenv sync --dev
    - name: Run tests
      if: "!contains(github.event.head_commit.message, 'skip ci')"
      shell: bash
      run: |
        mkdir arangodata
        export ARANGO=`pwd`/arangodb3-linux-$ARANGODB_VER/bin/arangodb
        export ARANGOD=`pwd`/arangodb3-linux-$ARANGODB_VER/usr/sbin/arangod
        $ARANGO start --server.arangod=$ARANGOD --starter.mode single --starter.data-dir ./arangodata
        PYTHONPATH=$(pwd):$(pwd)/src pipenv run make test
        $ARANGO stop
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./cov.xml
        fail_ci_if_error: true
